#!/usr/bin/env python
''' MinecraftSheet.py - Class for defining the Minecraft SpriteSheet class and all of the img frames within the sheet.'''

import sys
from Ledgrid import *

# ================================================================================
class MinecraftSheet(SpriteSheet):
    def __init__( self ):
        h = SpriteSheet.__init__( self, 'sprite_sheets/MinecraftSheet_24x20.png', stepx=16, stepy=16, offsetx=0, offsety=0 ) 

        # Row 0
        step = 16
        self.defineSprite( 'grassy_ground',             0 *step, 0*step )
        self.defineSprite( '',                          1 *step, 0*step )
        self.defineSprite( 'dirt',                      2 *step, 0*step )
        self.defineSprite( 'dirt_with_grass',           3 *step, 0*step )
        self.defineSprite( 'wood',                      4 *step, 0*step )
        self.defineSprite( 'cobblestone',               5 *step, 0*step )
        self.defineSprite( '',                          6 *step, 0*step )
        self.defineSprite( 'brick',                     7 *step, 0*step )
        self.defineSprite( 'tnt',                       8 *step, 0*step )
        self.defineSprite( '',                          9 *step, 0*step )
        self.defineSprite( '',                          10*step, 0*step )
        self.defineSprite( 'cobweb',                    11*step, 0*step )
        self.defineSprite( 'rose',                      12*step, 0*step )
        self.defineSprite( 'dandelion',                 13*step, 0*step )
        self.defineSprite( '',                          14*step, 0*step )
        self.defineSprite( 'tree',                      15*step, 0*step )
        self.defineSprite( '',                          16*step, 0*step )
        self.defineSprite( '',                          17*step, 0*step )
        self.defineSprite( '',                          18*step, 0*step )
        self.defineSprite( '',                          19*step, 0*step )
        self.defineSprite( '',                          20*step, 0*step )
        self.defineSprite( '',                          21*step, 0*step )
        self.defineSprite( '',                          22*step, 0*step )
        self.defineSprite( '',                          23*step, 0*step )

        self.defineSprite( 'stone',                     0 *step, 1*step )
        self.defineSprite( 'rock_coal',                 1 *step, 1*step )
        self.defineSprite( 'limestone',                 2 *step, 1*step )
        self.defineSprite( '',                          3 *step, 1*step )
        self.defineSprite( '',                          4 *step, 1*step )
        self.defineSprite( 'tree2',                     5 *step, 1*step )
        self.defineSprite( '',                          6 *step, 1*step )
        self.defineSprite( '',                          7 *step, 1*step )
        self.defineSprite( '',                          8 *step, 1*step )
        self.defineSprite( '',                          9 *step, 1*step )
        self.defineSprite( '',                          10*step, 1*step )
        self.defineSprite( '',                          11*step, 1*step )
        self.defineSprite( 'red_mushroom',              12*step, 1*step )
        self.defineSprite( 'mushroom',                  13*step, 1*step )
        self.defineSprite( 'shrub',                     14*step, 1*step )
        self.defineSprite( '',                          15*step, 1*step )
        self.defineSprite( '',                          16*step, 1*step )
        self.defineSprite( '',                          17*step, 1*step )
        self.defineSprite( '',                          18*step, 1*step )
        self.defineSprite( '',                          19*step, 1*step )
        self.defineSprite( '',                          20*step, 1*step )
        self.defineSprite( '',                          21*step, 1*step )
        self.defineSprite( '',                          22*step, 1*step )
        self.defineSprite( '',                          23*step, 1*step )

        self.defineSprite( 'rock_gold',                 0 *step, 2*step )
        self.defineSprite( 'rock_copper',               1 *step, 2*step )
        self.defineSprite( 'rock_coal2',                2 *step, 2*step )
        self.defineSprite( 'library',                   3 *step, 2*step )
        self.defineSprite( '',                          4 *step, 2*step )
        self.defineSprite( '',                          5 *step, 2*step )
        self.defineSprite( '',                          6 *step, 2*step )
        self.defineSprite( '',                          7 *step, 2*step )
        self.defineSprite( '',                          8 *step, 2*step )
        self.defineSprite( '',                          9 *step, 2*step )
        self.defineSprite( '',                          10*step, 2*step )
        self.defineSprite( '',                          11*step, 2*step )
        self.defineSprite( 'furnace1',                  12*step, 2*step )
        self.defineSprite( 'furnace2',                  13*step, 2*step )
        self.defineSprite( 'furnace3',                  14*step, 2*step )
        self.defineSprite( 'furnace4',                  15*step, 2*step )
        self.defineSprite( 'redstone_torch_lit',        16*step, 2*step )
        self.defineSprite( 'redstone_torch_unlit',      17*step, 2*step )
        self.defineSprite( 'redstone_dbl_torch_lit',    18*step, 2*step )
        self.defineSprite( '',                          19*step, 2*step )
        self.defineSprite( 'torch_lit',                 20*step, 2*step )
        self.defineSprite( 'torch_unlit',               21*step, 2*step )
        self.defineSprite( 'gear',                      22*step, 2*step )
        self.defineSprite( 'repeater_lit',              23*step, 2*step )

        self.defineSprite( '',                          0 *step, 3*step )
        self.defineSprite( 'glass',                     1 *step, 3*step )
        self.defineSprite( 'rock_diamond',              2 *step, 3*step )
        self.defineSprite( 'rock_readstone',            3 *step, 3*step )
        self.defineSprite( '',                          4 *step, 3*step )
        self.defineSprite( '',                          5 *step, 3*step )
        self.defineSprite( '',                          6 *step, 3*step )
        self.defineSprite( '',                          7 *step, 3*step )
        self.defineSprite( '',                          8 *step, 3*step )
        self.defineSprite( '',                          9 *step, 3*step )
        self.defineSprite( '',                          10*step, 3*step )
        self.defineSprite( '',                          11*step, 3*step )
        self.defineSprite( '',                          12*step, 3*step )
        self.defineSprite( 'furnace_lit',               13*step, 3*step )
        self.defineSprite( '',                          14*step, 3*step )
        self.defineSprite( '',                          15*step, 3*step )
        self.defineSprite( 'rose_yellow_flower',        16*step, 3*step )
        self.defineSprite( 'red_brown_mushroom',        17*step, 3*step )
        self.defineSprite( 'sign',                      18*step, 3*step )
        self.defineSprite( 'fire',                      19*step, 3*step )
        self.defineSprite( 'flower_garden',             20*step, 3*step )
        self.defineSprite( '',                          21*step, 3*step )
        self.defineSprite( '',                          22*step, 3*step )
        self.defineSprite( '',                          23*step, 3*step )

        self.defineSprite( '',                          0 *step, 4*step )
        self.defineSprite( '',                          1 *step, 4*step )
        self.defineSprite( '',                          2 *step, 4*step )
        self.defineSprite( '',                          3 *step, 4*step )
        self.defineSprite( '',                          4 *step, 4*step )
        self.defineSprite( 'cactus1',                   5 *step, 4*step )
        self.defineSprite( 'cactus2',                   6 *step, 4*step )
        self.defineSprite( '',                          7 *step, 4*step )
        self.defineSprite( '',                          8 *step, 4*step )
        self.defineSprite( '',                          9 *step, 4*step )
        self.defineSprite( '',                          10*step, 4*step )
        self.defineSprite( '',                          11*step, 4*step )
        self.defineSprite( '',                          12*step, 4*step )
        self.defineSprite( '',                          13*step, 4*step )
        self.defineSprite( '',                          14*step, 4*step )
        self.defineSprite( '',                          15*step, 4*step )
        self.defineSprite( '',                          16*step, 4*step )
        self.defineSprite( '',                          17*step, 4*step )
        self.defineSprite( '',                          18*step, 4*step )
        self.defineSprite( '',                          19*step, 4*step )
        self.defineSprite( '',                          20*step, 4*step )
        self.defineSprite( 'cobweb2',                   21*step, 4*step )
        self.defineSprite( '',                          22*step, 4*step )
        self.defineSprite( '',                          23*step, 4*step )

        self.defineSprite( 'torch_lit2',                0 *step, 5*step )
        self.defineSprite( 'door_window_handle',        1 *step, 5*step )
        self.defineSprite( 'door_window_white',         2 *step, 5*step )
        self.defineSprite( 'ladder',                    3 *step, 5*step )
        self.defineSprite( '',                          4 *step, 5*step )
        self.defineSprite( '',                          5 *step, 5*step )
        self.defineSprite( '',                          6 *step, 5*step )
        self.defineSprite( '',                          7 *step, 5*step )
        self.defineSprite( 'wheat1',                    8 *step, 5*step )
        self.defineSprite( 'wheat2',                    9 *step, 5*step )
        self.defineSprite( 'wheat3',                    10*step, 5*step )
        self.defineSprite( 'wheat4',                    11*step, 5*step )
        self.defineSprite( 'wheat5',                    12*step, 5*step )
        self.defineSprite( 'wheat6',                    13*step, 5*step )
        self.defineSprite( 'wheat7',                    14*step, 5*step )
        self.defineSprite( 'wheat8',                    15*step, 5*step )
        self.defineSprite( '',                          16*step, 5*step )
        self.defineSprite( '',                          17*step, 5*step )
        self.defineSprite( '',                          18*step, 5*step )
        self.defineSprite( '',                          19*step, 5*step )
        self.defineSprite( '',                          20*step, 5*step )
        self.defineSprite( '',                          21*step, 5*step )
        self.defineSprite( '',                          22*step, 5*step )
        self.defineSprite( '',                          23*step, 5*step )

        self.defineSprite( 'torch_unlit2',              0 *step, 6*step )
        self.defineSprite( 'door_window_nohandle',      1 *step, 6*step )
        self.defineSprite( 'door_nowindow_white',       2 *step, 6*step )
        self.defineSprite( 'torch_redstone2',           3 *step, 6*step )
        self.defineSprite( '',                          4 *step, 6*step )
        self.defineSprite( '',                          5 *step, 6*step )
        self.defineSprite( 'pumpkin_top',               6 *step, 6*step )
        self.defineSprite( '',                          7 *step, 6*step )
        self.defineSprite( '',                          8 *step, 6*step )
        self.defineSprite( '',                          9 *step, 6*step )
        self.defineSprite( '',                          10*step, 6*step )
        self.defineSprite( '',                          11*step, 6*step )
        self.defineSprite( '',                          12*step, 6*step )
        self.defineSprite( '',                          13*step, 6*step )
        self.defineSprite( '',                          14*step, 6*step )
        self.defineSprite( '',                          15*step, 6*step )
        self.defineSprite( '',                          16*step, 6*step )
        self.defineSprite( '',                          17*step, 6*step )
        self.defineSprite( '',                          18*step, 6*step )
        self.defineSprite( 'chest',                     19*step, 6*step )
        self.defineSprite( 'chest2wide_front',          20*step, 6*step )
        #self.defineSprite( '',                         21*step, 6*step )
        self.defineSprite( 'chest2wide_back',           22*step, 6*step )
        #self.defineSprite( '',                         23*step, 6*step )

        self.defineSprite( 'track_N_to_E',              0 *step, 7*step )
        self.defineSprite( '',                          1 *step, 7*step )
        self.defineSprite( '',                          2 *step, 7*step )
        self.defineSprite( 'torch_dead',                3 *step, 7*step )
        self.defineSprite( '',                          4 *step, 7*step )
        self.defineSprite( '',                          5 *step, 7*step )
        self.defineSprite( 'pumpkin_back',              6 *step, 7*step )
        self.defineSprite( 'pumpkin_front_unlit',       7 *step, 7*step )
        self.defineSprite( 'pumpkin_frong_lit',         8 *step, 7*step )
        self.defineSprite( '',                          9 *step, 7*step )
        self.defineSprite( '',                          10*step, 7*step )
        self.defineSprite( '',                          11*step, 7*step )
        self.defineSprite( '',                          12*step, 7*step )
        self.defineSprite( '',                          13*step, 7*step )
        self.defineSprite( '',                          14*step, 7*step )
        self.defineSprite( '',                          15*step, 7*step )
        self.defineSprite( '',                          16*step, 7*step )
        self.defineSprite( '',                          17*step, 7*step )
        self.defineSprite( '',                          18*step, 7*step )
        self.defineSprite( '',                          19*step, 7*step )
        self.defineSprite( '',                          20*step, 7*step )
        self.defineSprite( '',                          21*step, 7*step )
        self.defineSprite( '',                          22*step, 7*step )
        self.defineSprite( '',                          23*step, 7*step )

        self.defineSprite( 'track_NS',                  0 *step, 8*step )
        self.defineSprite( '',                          1 *step, 8*step )
        self.defineSprite( '',                          2 *step, 8*step )
        self.defineSprite( '',                          3 *step, 8*step )
        self.defineSprite( '',                          4 *step, 8*step )
        self.defineSprite( '',                          5 *step, 8*step )
        self.defineSprite( '',                          6 *step, 8*step )
        self.defineSprite( '',                          7 *step, 8*step )
        self.defineSprite( '',                          8 *step, 8*step )
        self.defineSprite( '',                          9 *step, 8*step )
        self.defineSprite( '',                          10*step, 8*step )
        self.defineSprite( '',                          11*step, 8*step )
        self.defineSprite( 'cake',                      12*step, 8*step )
        self.defineSprite( '',                          13*step, 8*step )
        self.defineSprite( '',                          14*step, 8*step )
        self.defineSprite( '',                          15*step, 8*step )
        self.defineSprite( '',                          16*step, 8*step )
        self.defineSprite( '',                          17*step, 8*step )
        self.defineSprite( '',                          18*step, 8*step )
        self.defineSprite( '',                          19*step, 8*step )
        self.defineSprite( '',                          20*step, 8*step )
        self.defineSprite( '',                          21*step, 8*step )
        self.defineSprite( '',                          22*step, 8*step )
        self.defineSprite( 'potted_rose',               23*step, 8*step )

        self.defineSprite( '',                          0 *step, 9*step )
        self.defineSprite( '',                          1 *step, 9*step )
        self.defineSprite( '',                          2 *step, 9*step )
        self.defineSprite( '',                          3 *step, 9*step )
        self.defineSprite( '',                          4 *step, 9*step )
        self.defineSprite( 'bed_from_toe',              5 *step, 9*step )
        self.defineSprite( 'bed_from_side',             6 *step, 9*step )
        self.defineSprite( 'bed_from_head',             7 *step, 9*step )
        self.defineSprite( '',                          8 *step, 9*step )
        self.defineSprite( '',                          9 *step, 9*step )
        self.defineSprite( '',                          10*step, 9*step )
        self.defineSprite( '',                          11*step, 9*step )
        self.defineSprite( '',                          12*step, 9*step )
        self.defineSprite( '',                          13*step, 9*step )
        self.defineSprite( '',                          14*step, 9*step )
        self.defineSprite( '',                          15*step, 9*step )
        self.defineSprite( '',                          16*step, 9*step )
        self.defineSprite( 'skeleton_head',             17*step, 9*step )
        self.defineSprite( 'wither_skeleton_head',      18*step, 9*step )
        self.defineSprite( 'zombie_head',               19*step, 9*step )
        self.defineSprite( 'player_head',               20*step, 9*step )
        self.defineSprite( 'creeper_head',              21*step, 9*step )
        self.defineSprite( 'multi_heads',               22*step, 9*step )
        self.defineSprite( '',                          23*step, 9*step )

        self.defineSprite( '',                          0 *step, 10*step )
        self.defineSprite( '',                          1 *step, 10*step )
        self.defineSprite( '',                          2 *step, 10*step )
        self.defineSprite( 'yel_tracks_redstone_off',   3 *step, 10*step )
        self.defineSprite( 'redstone_cross_lit',        4 *step, 10*step )
        self.defineSprite( 'redstone_horiz_lit',        5 *step, 10*step )
        self.defineSprite( '',                          6 *step, 10*step )
        self.defineSprite( '',                          7 *step, 10*step )
        self.defineSprite( '',                          8 *step, 10*step )
        self.defineSprite( '',                          9 *step, 10*step )
        self.defineSprite( '',                          10*step, 10*step )
        self.defineSprite( '',                          11*step, 10*step )
        self.defineSprite( '',                          12*step, 10*step )
        self.defineSprite( '',                          13*step, 10*step )
        self.defineSprite( '',                          14*step, 10*step )
        self.defineSprite( '',                          15*step, 10*step )
        self.defineSprite( '',                          16*step, 10*step )
        self.defineSprite( '',                          17*step, 10*step )
        self.defineSprite( '',                          18*step, 10*step )
        self.defineSprite( '',                          19*step, 10*step )
        self.defineSprite( '',                          20*step, 10*step )
        self.defineSprite( '',                          21*step, 10*step )
        self.defineSprite( '',                          22*step, 10*step )
        self.defineSprite( '',                          23*step, 10*step )

        self.defineSprite( '',                          0 *step, 11*step )
        self.defineSprite( '',                          1 *step, 11*step )
        self.defineSprite( '',                          2 *step, 11*step )
        self.defineSprite( 'yel_tracks_redstone_on',    3 *step, 11*step )
        self.defineSprite( 'redstone_cross_unlit',      4 *step, 11*step )
        self.defineSprite( 'redstone_horiz_unlit',      5 *step, 11*step )
        self.defineSprite( '',                          6 *step, 11*step )
        self.defineSprite( '',                          7 *step, 11*step )
        self.defineSprite( '',                          8 *step, 11*step )
        self.defineSprite( '',                          9 *step, 11*step )
        self.defineSprite( '',                          10*step, 11*step )
        self.defineSprite( '',                          11*step, 11*step )
        self.defineSprite( '',                          12*step, 11*step )
        self.defineSprite( '',                          13*step, 11*step )
        self.defineSprite( '',                          14*step, 11*step )
        self.defineSprite( '',                          15*step, 11*step )
        self.defineSprite( '',                          16*step, 11*step )
        self.defineSprite( '',                          17*step, 11*step )
        self.defineSprite( '',                          18*step, 11*step )
        self.defineSprite( '',                          19*step, 11*step )
        self.defineSprite( '',                          20*step, 11*step )
        self.defineSprite( 'track_E_to_S',              21*step, 11*step )
        self.defineSprite( 'track_S_to_W',              22*step, 11*step )
        self.defineSprite( 'track_W_to_N',              23*step, 11*step )

        self.defineSprite( '',                          0 *step, 12*step )
        self.defineSprite( '',                          1 *step, 12*step )
        self.defineSprite( '',                          2 *step, 12*step )
        self.defineSprite( 'tracks_repeater_unlit',     3 *step, 12*step )
        self.defineSprite( '',                          4 *step, 12*step )
        self.defineSprite( '',                          5 *step, 12*step )
        self.defineSprite( '',                          6 *step, 12*step )
        self.defineSprite( '',                          7 *step, 12*step )
        self.defineSprite( 'grass1',                    8 *step, 12*step )
        self.defineSprite( 'grass2',                    9 *step, 12*step )
        self.defineSprite( 'grass3',                    10*step, 12*step )
        self.defineSprite( 'grass4',                    11*step, 12*step )
        self.defineSprite( 'grass5',                    12*step, 12*step )
        self.defineSprite( '',                          13*step, 12*step )
        self.defineSprite( '',                          14*step, 12*step )
        self.defineSprite( '',                          15*step, 12*step )
        self.defineSprite( 'rail_EW',                   16*step, 12*step )
        self.defineSprite( '',                          17*step, 12*step )
        self.defineSprite( '',                          18*step, 12*step )
        self.defineSprite( '',                          19*step, 12*step )
        self.defineSprite( 'brick2',                    20*step, 12*step )
        self.defineSprite( '',                          21*step, 12*step )
        self.defineSprite( '',                          22*step, 12*step )
        self.defineSprite( 'tracks_repeater_lit',       23*step, 12*step )

        self.defineSprite( '',                          0 *step, 13*step )
        self.defineSprite( '',                          1 *step, 13*step )
        self.defineSprite( '',                          2 *step, 13*step )
        self.defineSprite( '',                          3 *step, 13*step )
        self.defineSprite( '',                          4 *step, 13*step )
        self.defineSprite( '',                          5 *step, 13*step )
        self.defineSprite( '',                          6 *step, 13*step )
        self.defineSprite( '',                          7 *step, 13*step )
        self.defineSprite( '',                          8 *step, 13*step )
        self.defineSprite( 'tracks_redstone_on',        9 *step, 13*step )
        self.defineSprite( 'tracks_redstone_off',       10*step, 13*step )
        self.defineSprite( '',                          11*step, 13*step )
        self.defineSprite( '',                          12*step, 13*step )
        self.defineSprite( '',                          13*step, 13*step )
        self.defineSprite( '',                          14*step, 13*step )
        self.defineSprite( '',                          15*step, 13*step )
        self.defineSprite( '',                          16*step, 13*step )
        self.defineSprite( '',                          17*step, 13*step )
        self.defineSprite( '',                          18*step, 13*step )
        self.defineSprite( '',                          19*step, 13*step )
        self.defineSprite( '',                          20*step, 13*step )
        self.defineSprite( '',                          21*step, 13*step )
        self.defineSprite( '',                          22*step, 13*step )
        self.defineSprite( '',                          23*step, 13*step )

        self.defineSprite( '',                          0 *step, 14*step )
        self.defineSprite( '',                          1 *step, 14*step )
        self.defineSprite( '',                          2 *step, 14*step )
        self.defineSprite( '',                          3 *step, 14*step )
        self.defineSprite( '',                          4 *step, 14*step )
        self.defineSprite( '',                          5 *step, 14*step )
        self.defineSprite( '',                          6 *step, 14*step )
        self.defineSprite( '',                          7 *step, 14*step )
        self.defineSprite( '',                          8 *step, 14*step )
        self.defineSprite( '',                          9 *step, 14*step )
        self.defineSprite( '',                          10*step, 14*step )
        self.defineSprite( '',                          11*step, 14*step )
        self.defineSprite( '',                          12*step, 14*step )
        self.defineSprite( '',                          13*step, 14*step )
        self.defineSprite( '',                          14*step, 14*step )
        self.defineSprite( '',                          15*step, 14*step )
        self.defineSprite( '',                          16*step, 14*step )
        self.defineSprite( '',                          17*step, 14*step )
        self.defineSprite( '',                          18*step, 14*step )
        self.defineSprite( '',                          19*step, 14*step )
        self.defineSprite( '',                          20*step, 14*step )
        self.defineSprite( '',                          21*step, 14*step )
        self.defineSprite( '',                          22*step, 14*step )
        self.defineSprite( '',                          23*step, 14*step )

        self.defineSprite( '',                          0 *step, 15*step )
        self.defineSprite( '',                          1 *step, 15*step )
        self.defineSprite( '',                          2 *step, 15*step )
        self.defineSprite( '',                          3 *step, 15*step )
        self.defineSprite( '',                          4 *step, 15*step )
        self.defineSprite( '',                          5 *step, 15*step )
        self.defineSprite( '',                          6 *step, 15*step )
        self.defineSprite( '',                          7 *step, 15*step )
        self.defineSprite( '',                          8 *step, 15*step )
        self.defineSprite( '',                          9 *step, 15*step )
        self.defineSprite( '',                          10*step, 15*step )
        self.defineSprite( '',                          11*step, 15*step )
        self.defineSprite( '',                          12*step, 15*step )
        self.defineSprite( '',                          13*step, 15*step )
        self.defineSprite( '',                          14*step, 15*step )
        self.defineSprite( '',                          15*step, 15*step )
        self.defineSprite( '',                          16*step, 15*step )
        self.defineSprite( '',                          17*step, 15*step )
        self.defineSprite( '',                          18*step, 15*step )
        self.defineSprite( '',                          19*step, 15*step )
        self.defineSprite( '',                          20*step, 15*step )
        self.defineSprite( '',                          21*step, 15*step )
        self.defineSprite( '',                          22*step, 15*step )
        self.defineSprite( '',                          23*step, 15*step )

        self.defineSprite( '',                          0 *step, 16*step )
        self.defineSprite( '',                          1 *step, 16*step )
        self.defineSprite( '',                          2 *step, 16*step )
        self.defineSprite( '',                          3 *step, 16*step )
        self.defineSprite( '',                          4 *step, 16*step )
        self.defineSprite( '',                          5 *step, 16*step )
        self.defineSprite( '',                          6 *step, 16*step )
        self.defineSprite( '',                          7 *step, 16*step )
        self.defineSprite( '',                          8 *step, 16*step )
        self.defineSprite( '',                          9 *step, 16*step )
        self.defineSprite( '',                          10*step, 16*step )
        self.defineSprite( '',                          11*step, 16*step )
        self.defineSprite( '',                          12*step, 16*step )
        self.defineSprite( '',                          13*step, 16*step )
        self.defineSprite( '',                          14*step, 16*step )
        self.defineSprite( '',                          15*step, 16*step )
        self.defineSprite( '',                          16*step, 16*step )
        self.defineSprite( '',                          17*step, 16*step )
        self.defineSprite( '',                          18*step, 16*step )
        self.defineSprite( '',                          19*step, 16*step )
        self.defineSprite( '',                          20*step, 16*step )
        self.defineSprite( '',                          21*step, 16*step )
        self.defineSprite( '',                          22*step, 16*step )
        self.defineSprite( '',                          23*step, 16*step )

        self.defineSprite( '',                          0 *step, 17*step )
        self.defineSprite( '',                          1 *step, 17*step )
        self.defineSprite( '',                          2 *step, 17*step )
        self.defineSprite( '',                          3 *step, 17*step )
        self.defineSprite( '',                          4 *step, 17*step )
        self.defineSprite( '',                          5 *step, 17*step )
        self.defineSprite( '',                          6 *step, 17*step )
        self.defineSprite( '',                          7 *step, 17*step )
        self.defineSprite( '',                          8 *step, 17*step )
        self.defineSprite( '',                          9 *step, 17*step )
        self.defineSprite( '',                          10*step, 17*step )
        self.defineSprite( '',                          11*step, 17*step )
        self.defineSprite( '',                          12*step, 17*step )
        self.defineSprite( '',                          13*step, 17*step )
        self.defineSprite( '',                          14*step, 17*step )
        self.defineSprite( '',                          15*step, 17*step )
        self.defineSprite( '',                          16*step, 17*step )
        self.defineSprite( '',                          17*step, 17*step )
        self.defineSprite( '',                          18*step, 17*step )
        self.defineSprite( '',                          19*step, 17*step )
        self.defineSprite( '',                          20*step, 17*step )
        self.defineSprite( '',                          21*step, 17*step )
        self.defineSprite( '',                          22*step, 17*step )
        self.defineSprite( '',                          23*step, 17*step )

        self.defineSprite( '',                          0 *step, 18*step )
        self.defineSprite( '',                          1 *step, 18*step )
        self.defineSprite( '',                          2 *step, 18*step )
        self.defineSprite( '',                          3 *step, 18*step )
        self.defineSprite( '',                          4 *step, 18*step )
        self.defineSprite( '',                          5 *step, 18*step )
        self.defineSprite( '',                          6 *step, 18*step )
        self.defineSprite( '',                          7 *step, 18*step )
        self.defineSprite( '',                          8 *step, 18*step )
        self.defineSprite( '',                          9 *step, 18*step )
        self.defineSprite( '',                          10*step, 18*step )
        self.defineSprite( '',                          11*step, 18*step )
        self.defineSprite( '',                          12*step, 18*step )
        self.defineSprite( '',                          13*step, 18*step )
        self.defineSprite( '',                          14*step, 18*step )
        self.defineSprite( '',                          15*step, 18*step )
        self.defineSprite( '',                          16*step, 18*step )
        self.defineSprite( '',                          17*step, 18*step )
        self.defineSprite( '',                          18*step, 18*step )
        self.defineSprite( '',                          19*step, 18*step )
        self.defineSprite( '',                          20*step, 18*step )
        self.defineSprite( '',                          21*step, 18*step )
        self.defineSprite( '',                          22*step, 18*step )
        self.defineSprite( '',                          23*step, 18*step )

        self.defineSprite( '',                          0 *step, 19*step )
        self.defineSprite( '',                          1 *step, 19*step )
        self.defineSprite( '',                          2 *step, 19*step )
        self.defineSprite( '',                          3 *step, 19*step )
        self.defineSprite( '',                          4 *step, 19*step )
        self.defineSprite( '',                          5 *step, 19*step )
        self.defineSprite( '',                          6 *step, 19*step )
        self.defineSprite( '',                          7 *step, 19*step )
        self.defineSprite( '',                          8 *step, 19*step )
        self.defineSprite( '',                          9 *step, 19*step )
        self.defineSprite( '',                          10*step, 19*step )
        self.defineSprite( '',                          11*step, 19*step )
        self.defineSprite( '',                          12*step, 19*step )
        self.defineSprite( '',                          13*step, 19*step )
        self.defineSprite( '',                          14*step, 19*step )
        self.defineSprite( '',                          15*step, 19*step )
        self.defineSprite( '',                          16*step, 19*step )
        self.defineSprite( '',                          17*step, 19*step )
        self.defineSprite( '',                          18*step, 19*step )
        self.defineSprite( '',                          19*step, 19*step )
        self.defineSprite( '',                          20*step, 19*step )
        self.defineSprite( '',                          21*step, 19*step )
        self.defineSprite( '',                          22*step, 19*step )
        self.defineSprite( '',                          23*step, 19*step )


        #self.defineSprite( 'glass', 64, 272 )
        self.defineSprite( 'lava', 176, 288 )
        #self.defineSprite( 'tracks_redstone_on', 144, 208 )
        #self.defineSprite( 'tracks_redstone_off', 144, 224 )
        #self.defineSprite( 'yel_tracks_redstone_on', 48, 176 )
        #self.defineSprite( 'yel_tracks_redstone_off', 48, 160 )
        #self.defineSprite( 'grass1', 128, 192 )
        #self.defineSprite( 'grass2', 144, 192 )
        #self.defineSprite( 'grass3', 160, 192 )
        #self.defineSprite( 'grass4', 176, 192 )
        #self.defineSprite( 'torch_on', 48, 96 )
        #self.defineSprite( 'torch_off', 48, 112 )
        #self.defineSprite( 'ladder', 48, 80 )
        #self.defineSprite( 'wheat1', 128, 80 )
        #self.defineSprite( 'wheat2', 144, 80 )
        #self.defineSprite( 'wheat3', 160, 80 )
        #self.defineSprite( 'wheat4', 176, 80 )
        #self.defineSprite( 'wheat5', 192, 80 )
        #self.defineSprite( 'wheat6', 208, 80 )
        #self.defineSprite( 'wheat7', 224, 80 )
        #self.defineSprite( 'wheat8', 240, 80 )
        return( h )

# ================================================================================
if __name__ == '__main__':
    # Use the SpriteSheet.exploresheet() method to display the sprites & determine their coords:
    if False:
        ss = SpriteSheet( 'sprite_sheets/mrs_pacman_16x16.png', stepx=16, stepy=16, offsetx=0, offsety=0 )
        grid = Ledgrid()
        grid.exploreSheet( ss )
        grid.clear()
        grid.close()
        sys.exit(0)
        
    # Use the AnimationSequence.addFrame() method to define a sequences of images for an animation:
    if True:        
        minecraft_ss = MinecraftSheet();
        dur_short = 100
        dur_medium = 150
        dur_long = 350

        seq1 = AnimationSequence("seq1")
        seq1.addFrame( minecraft_ss, 'wheat1', duration_ms=dur_short )
        seq1.addFrame( minecraft_ss, 'wheat2', duration_ms=dur_short )
        seq1.addFrame( minecraft_ss, 'wheat3', duration_ms=dur_short )
        seq1.addFrame( minecraft_ss, 'wheat4', duration_ms=dur_short )
        seq1.addFrame( minecraft_ss, 'wheat5', duration_ms=dur_short )
        seq1.addFrame( minecraft_ss, 'wheat6', duration_ms=dur_short )
        seq1.addFrame( minecraft_ss, 'wheat7', duration_ms=dur_short )
        seq1.addFrame( minecraft_ss, 'wheat8', duration_ms=dur_short )
        seq1.addFrame( minecraft_ss, 'glass', duration_ms=dur_medium )
        seq1.addFrame( minecraft_ss, 'lava', duration_ms=dur_medium )
        seq1.addFrame( minecraft_ss, 'tracks_redstone_on', duration_ms=dur_long )
        seq1.addFrame( minecraft_ss, 'tracks_redstone_off', duration_ms=dur_long )
        seq1.addFrame( minecraft_ss, 'yel_tracks_redstone_on', duration_ms=dur_long )
        seq1.addFrame( minecraft_ss, 'yel_tracks_redstone_off', duration_ms=dur_long )
        seq1.addFrame( minecraft_ss, 'grass1', duration_ms=dur_medium )
        seq1.addFrame( minecraft_ss, 'grass2', duration_ms=dur_medium )
        seq1.addFrame( minecraft_ss, 'grass3', duration_ms=dur_medium )
        seq1.addFrame( minecraft_ss, 'grass4', duration_ms=dur_medium )
        seq1.addFrame( minecraft_ss, 'torch_lit', duration_ms=dur_long )
        seq1.addFrame( minecraft_ss, 'torch_unlit', duration_ms=dur_long )
        seq1.addFrame( minecraft_ss, 'ladder', duration_ms=dur_long )

        grid = Ledgrid()
        grid.showSequence( seq1, printinfo=False )
        grid.clear()
        grid.close()
        sys.exit(0)
